import { ACHIEVEMENTS, HABITS, HEIGHT_METRES, START_WEIGHT, WEEKLY_TARGETS, WORKOUTS } from '../data/programme.js';
import { exportState, loadState, resetState, saveState, today } from './storage.js';
import { WorkoutPlayer } from './workout-player.js';

let state = loadState(); let route = 'home'; let selectedWorkout = null; let chart = null; let installPrompt = null;
const $ = selector => document.querySelector(selector);
const localDate = date => new Date(`${date}T12:00:00`).toLocaleDateString(undefined, { day: 'numeric', month: 'short' });
const dayDifference = date => Math.max(0, Math.floor((new Date(today()) - new Date(`${date}T00:00:00`)) / 86400000));
const currentWeek = () => Math.min(12, Math.floor(dayDifference(state.startedAt) / 7) + 1);
const intervals = () => currentWeek() <= 4 ? [40, 20] : currentWeek() <= 8 ? [45, 15] : [50, 10];
const currentWeight = () => state.checkins.at(-1)?.weight ?? null;
const latestCheckin = () => state.checkins.at(-1) ?? null;
const workoutForToday = () => Object.entries(WORKOUTS).find(([, workout]) => workout.days.includes(new Date().getDay() || 7))?.[0] ?? 'Full Body';
function sessionStreak() { const dates = new Set(state.sessions.map(session => session.date)); let check = new Date(); let count = 0; for (;;) { const date = check.toISOString().slice(0, 10); if (dates.has(date)) { count += 1; check.setDate(check.getDate() - 1); continue; } if (count === 0) { check.setDate(check.getDate() - 1); if (dates.has(check.toISOString().slice(0, 10))) { count += 1; check.setDate(check.getDate() - 1); continue; } } break; } return count; }
function weeklySessions() { const start = new Date(); start.setDate(start.getDate() - ((start.getDay() + 6) % 7)); return state.sessions.filter(session => session.date >= start.toISOString().slice(0, 10)).length; }
function metrics() { const weight = currentWeight(); const recent = state.checkins.filter(checkin => dayDifference(checkin.date) < 7); return { weight, streak: sessionStreak(), lost: weight ? Math.max(0, START_WEIGHT - weight) : 0, bmi: weight ? weight / (HEIGHT_METRES ** 2) : null, weeklyAverage: recent.length ? recent.reduce((total, checkin) => total + checkin.weight, 0) / recent.length : null }; }
function persist() { saveState(state); render(); }
function voice(text, force = false) { if ((!state.settings.voice && !force) || !('speechSynthesis' in window)) return; speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.lang = 'en-GB'; utterance.rate = .96; utterance.pitch = .94; speechSynthesis.speak(utterance); }
const player = new WorkoutPlayer({ onUpdate: renderPlayer, onComplete: completeWorkout, speak: voice });

function render() { applyTheme(); renderHome(); renderWorkoutLibrary(); renderProgress(); renderCalendar(); renderAchievements(); renderSettings(); }
function renderHome() { const m = metrics(), week = currentWeek(), [work, rest] = intervals(), name = workoutForToday(), workout = WORKOUTS[name], habits = state.habits[today()] || {}; $('#week-label').textContent = `WEEK ${week} OF 12`; $('#progress-percent').textContent = `${Math.round(((week - 1) / 12) * 100)}% complete`; $('#programme-progress').style.width = `${Math.max(3, ((week - 1) / 12) * 100)}%`; $('#current-weight').innerHTML = m.weight ? `${m.weight.toFixed(1)} <em>kg</em>` : '— <em>kg</em>'; $('#weekly-target').innerHTML = `${WEEKLY_TARGETS[week - 1].toFixed(1)} <em>kg</em>`; $('#today-workout').textContent = name; $('#today-workout-icon').textContent = workout.icon; $('#today-workout-detail').textContent = `10 min · ${work} sec work / ${rest} sec recover`; $('#streak').textContent = `${m.streak} day${m.streak === 1 ? '' : 's'}`; $('#sessions').textContent = state.sessions.length; $('#weight-lost').textContent = `${m.lost.toFixed(1)} kg`; $('#coach-message').querySelector('p').textContent = coachMessage(m); $('#habits').innerHTML = HABITS.map(habit => `<div class="habit"><label><input type="checkbox" data-habit="${habit.id}" ${habits[habit.id] ? 'checked' : ''}><span>${habit.label}</span></label></div>`).join(''); $('#habit-score').textContent = `${Object.values(habits).filter(Boolean).length} / ${HABITS.length}`; $('#habits').querySelectorAll('input').forEach(input => input.addEventListener('change', () => { state.habits[today()] = { ...state.habits[today()], [input.dataset.habit]: input.checked }; persist(); })); }
function coachMessage(m) { if (m.weight && m.weight < 100) return 'You did it — double digits. Keep building the life that got you here.'; if (weeklySessions() >= 4) return `You've completed ${weeklySessions()} workouts this week. This is where habits become lifestyle.`; if (m.streak >= 3) return `${m.streak} days of momentum. Keep the promise you made to yourself.`; return 'One workout closer to double digits.'; }
function renderWorkoutLibrary() { const [work, rest] = intervals(); selectedWorkout ||= workoutForToday(); $('#workout-types').innerHTML = Object.entries(WORKOUTS).map(([name, workout]) => `<button class="workout-type ${selectedWorkout === name ? 'is-selected' : ''}" data-workout="${name}"><span class="type-icon">${workout.icon}</span><span><strong>${name}</strong><small>${workout.exercises[0]} · ${work}/${rest}</small></span></button>`).join(''); $('#workout-types').querySelectorAll('button').forEach(button => button.addEventListener('click', () => { selectedWorkout = button.dataset.workout; renderWorkoutLibrary(); })); }
function renderPlayer(s) { $('#timer').textContent = `00:${String(s.remaining).padStart(2, '0')}`; $('#timer-circle').style.setProperty('--angle', `${s.angle}deg`); $('#timer-circle').style.background = `conic-gradient(${s.phase === 'work' ? 'var(--lime)' : 'var(--orange)'} var(--angle), rgba(96,132,119,.24) 0)`; $('#player-phase').textContent = s.phase === 'work' ? 'WORK' : 'RECOVER'; $('#timer-status').textContent = s.paused ? 'Paused' : s.phase === 'work' ? 'Keep moving' : 'Catch your breath'; $('#exercise-index').textContent = s.phase === 'work' ? `ROUND ${s.round} · EXERCISE ${s.index + 1} OF 5` : 'RECOVERY'; $('#exercise-name').textContent = s.phase === 'work' ? s.exercises[s.index] : 'Take a breath'; $('#next-exercise').textContent = s.phase === 'work' ? `Next: ${s.exercises[(s.index + 1) % 5]}` : 'Get ready for the next move'; $('#player-progress').style.width = `${s.progress * 100}%`; $('#pause-workout').textContent = s.paused ? 'RESUME' : 'PAUSE'; }
function completeWorkout() { state.sessions.push({ id: crypto.randomUUID?.() ?? `${Date.now()}`, date: today(), type: selectedWorkout }); state.habits[today()] = { ...state.habits[today()], workout: true }; saveState(state); $('#player').classList.add('is-hidden'); $('#workout-complete').classList.remove('is-hidden'); render(); voice('Workout complete. Outstanding effort. Under 100 is getting closer.'); }
function renderProgress() { const m = metrics(), latest = latestCheckin(); $('#latest-weight').textContent = m.weight ? `${m.weight.toFixed(1)} kg` : '— kg'; $('#bmi').textContent = m.bmi ? m.bmi.toFixed(1) : '—'; $('#latest-waist').textContent = latest?.waist ? `${latest.waist.toFixed(1)} cm` : '— cm'; $('#weekly-average').textContent = m.weeklyAverage ? `${m.weeklyAverage.toFixed(1)} kg` : '— kg'; $('#weight-history').innerHTML = state.checkins.length ? [...state.checkins].reverse().slice(0, 8).map(checkin => `<div class="history-row"><span>${localDate(checkin.date)} ${checkin.waist ? `<small>· ${checkin.waist} cm waist</small>` : ''}</span><b>${checkin.weight.toFixed(1)} kg</b></div>`).join('') : '<p class="subtitle">Your first check-in will show up here.</p>'; renderChart(); }
function renderChart() { const canvas = $('#weight-chart'); if (!window.Chart || !canvas) return; chart?.destroy(); const values = state.checkins.slice(-12); chart = new Chart(canvas, { type: 'line', data: { labels: values.map(value => localDate(value.date)), datasets: [{ data: values.map(value => value.weight), borderColor: '#daf65a', backgroundColor: 'rgba(218,246,90,.15)', pointBackgroundColor: '#daf65a', pointRadius: 4, fill: true, tension: .35 }] }, options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false }, tooltip: { displayColors: false } }, scales: { x: { grid: { display: false }, ticks: { color: '#a5b9b0', font: { size: 10 } } }, y: { grid: { color: 'rgba(235,247,238,.08)' }, ticks: { color: '#a5b9b0', font: { size: 10 } } } } } }); }
function renderCalendar() { const week = currentWeek(); $('#calendar-grid').innerHTML = WEEKLY_TARGETS.map((target, index) => { const number = index + 1; const sessionCount = state.sessions.filter(session => Math.max(0, Math.floor((new Date(`${session.date}T00:00:00`) - new Date(`${state.startedAt}T00:00:00`)) / 604800000)) === index).length; return `<article class="week-card ${number === week ? 'is-current' : ''}"><small>WEEK ${number}</small><b>${target.toFixed(1)} kg</b><span>${sessionCount ? `${sessionCount} sessions` : number < week ? 'Keep going' : number === week ? 'This week' : 'Ahead'}</span></article>`; }).join(''); const count = weeklySessions(), completeDays = Object.values(state.habits).filter(day => Object.values(day).filter(Boolean).length >= 4).length; $('#review-title').textContent = `${count} workout${count === 1 ? '' : 's'} this week`; $('#review-copy').textContent = count >= 4 ? 'Excellent consistency. This is how a goal becomes a lifestyle.' : 'Every session you complete is a vote for the person you are becoming.'; $('#review-stats').innerHTML = `<div><b>${count}</b><small>sessions</small></div><div><b>${completeDays}</b><small>strong days</small></div><div><b>${metrics().streak}</b><small>day streak</small></div>`; }
function renderAchievements() { const m = metrics(); $('#achievement-list').innerHTML = ACHIEVEMENTS.map(achievement => { const unlocked = achievement.unlocked(state, m); return `<article class="glass achievement ${unlocked ? '' : 'is-locked'}"><span class="badge">${achievement.icon}</span><span><strong>${achievement.title}</strong><small>${unlocked ? 'Unlocked — well earned.' : achievement.detail}</small></span></article>`; }).join(''); }
function renderSettings() { $('#setting-voice').checked = state.settings.voice; $('#setting-dark').checked = state.settings.dark; $('#setting-reminder').value = state.settings.reminder; $('#bluetooth-status').textContent = 'Connect your speaker in your phone’s Bluetooth settings, then use this test. Voice coaching follows your phone’s active audio route.'; }
function applyTheme() { document.body.classList.toggle('light', !state.settings.dark); }
function go(to) { if (!document.getElementById(to)) return; if (route === 'workout' && to !== 'workout') player.stop(); route = to; document.querySelectorAll('.screen').forEach(screen => screen.classList.toggle('is-active', screen.id === to)); document.querySelectorAll('.tab-bar button').forEach(button => button.classList.toggle('is-active', button.dataset.route === to)); window.scrollTo({ top: 0, behavior: 'smooth' }); if (to === 'workout') resetWorkoutView(); }
function resetWorkoutView() { $('#workout-library').classList.remove('is-hidden'); $('#player').classList.add('is-hidden'); $('#workout-complete').classList.add('is-hidden'); renderWorkoutLibrary(); }

document.querySelectorAll('[data-route]').forEach(button => button.addEventListener('click', () => go(button.dataset.route)));
$('#start-today').addEventListener('click', () => { selectedWorkout = workoutForToday(); go('workout'); });
$('#begin-workout').addEventListener('click', () => { $('#workout-library').classList.add('is-hidden'); $('#player').classList.remove('is-hidden'); player.start(selectedWorkout, intervals()); });
$('#pause-workout').addEventListener('click', () => player.togglePause()); $('#skip-workout').addEventListener('click', () => player.skip()); $('#exit-workout').addEventListener('click', () => go('home'));
$('#toggle-voice').addEventListener('click', () => { state.settings.voice = !state.settings.voice; persist(); $('#toggle-voice').textContent = state.settings.voice ? 'Voice on' : 'Voice off'; });
$('#weight-form').addEventListener('submit', event => { event.preventDefault(); const date = $('#checkin-date').value; const checkin = { date, weight: Number($('#checkin-weight').value), waist: Number($('#checkin-waist').value) || null }; state.checkins = state.checkins.filter(item => item.date !== date).concat(checkin).sort((a, b) => a.date.localeCompare(b.date)); event.target.reset(); $('#checkin-date').value = today(); persist(); });
$('#setting-voice').addEventListener('change', event => { state.settings.voice = event.target.checked; persist(); }); $('#setting-dark').addEventListener('change', event => { state.settings.dark = event.target.checked; persist(); }); $('#setting-reminder').addEventListener('change', event => { state.settings.reminder = event.target.value; persist(); }); $('#test-voice').addEventListener('click', () => voice('Project Under 100 is ready. Your voice coaching will play through the active speaker.', true)); $('#export-data').addEventListener('click', () => exportState(state)); $('#reset-data').addEventListener('click', () => { if (confirm('Reset all Project Under 100 data saved on this device?')) { state = resetState(); persist(); } });
$('#checkin-date').value = today(); window.addEventListener('beforeinstallprompt', event => { event.preventDefault(); installPrompt = event; $('#install-app').classList.remove('is-hidden'); }); $('#install-app').addEventListener('click', async () => { if (!installPrompt) return; installPrompt.prompt(); await installPrompt.userChoice; installPrompt = null; $('#install-app').classList.add('is-hidden'); }); if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('./sw.js')); render();
