/* Project Under 100 — private, offline-first fitness companion */
const PROGRAMME = {
  HIIT: { emoji: '⚡', days: [1,4], exercises: ['Squat + knee to elbow', 'Press-ups', 'Reverse lunge + knee drive', 'Mountain climbers', 'Squat thrusts'] },
  Strength: { emoji: '💪', days: [2], exercises: ['Slow squats', 'Press-ups', 'Alternating reverse lunges', 'Plank shoulder taps', 'Glute bridges'] },
  'Core & mobility': { emoji: '◎', days: [5], exercises: ['Dead bugs', 'Bicycle crunches', 'Plank', 'Slow mountain climbers', 'Side plank'] },
  'Full body': { emoji: '🔥', days: [6], exercises: ['Fast squats', 'Press-ups', 'Alternating lunges', 'Mountain climbers', 'Squat thrusts'] }
};
const TARGETS = [106.2,105.5,104.8,104.0,103.3,102.6,101.9,101.2,100.6,100.0,99.5,99.0];
const HABITS = ['Stayed within calorie target','Hit 160g protein','Completed workout','Walked 8,000+ steps','Drank 2.5L water','Slept 7+ hours'];
const KEY = 'project-under-100-v3';
let data = load(); let selectedWorkout = 'HIIT'; let timer = null; let timerState = null; let deferredInstall = null;

function load(){ try { return JSON.parse(localStorage.getItem(KEY)) || { startDate: new Date().toISOString().slice(0,10), habits: {}, sessions: [], weights: [], sound: true }; } catch { return { startDate: new Date().toISOString().slice(0,10), habits: {}, sessions: [], weights: [], sound: true }; } }
function save(){ localStorage.setItem(KEY, JSON.stringify(data)); render(); }
function today(){ return new Date().toISOString().slice(0,10); }
function dayDiff(date){ return Math.max(0, Math.floor((new Date(today()) - new Date(`${date}T00:00:00`)) / 86400000)); }
function week(){ return Math.min(12, Math.floor(dayDiff(data.startDate)/7) + 1); }
function intervals(){ const w=week(); return w<=4 ? [40,20] : w<=8 ? [45,15] : [50,10]; }
function workoutForToday(){ const d = new Date().getDay() || 7; return Object.entries(PROGRAMME).find(([,v])=>v.days.includes(d))?.[0] || 'Full body'; }
function dateText(d){ return new Date(`${d}T12:00:00`).toLocaleDateString(undefined,{day:'numeric',month:'short'}); }
function streak(){ const dates=[...new Set(data.sessions.map(s=>s.date))].sort().reverse(); let count=0, check=new Date(); for(const date of dates){ const expected=check.toISOString().slice(0,10); if(date===expected){count++;check.setDate(check.getDate()-1)} else if(count===0){check.setDate(check.getDate()-1); if(date===check.toISOString().slice(0,10)){count++;check.setDate(check.getDate()-1)} else break;} else break; } return count; }
function currentWeight(){ return data.weights.length ? data.weights.at(-1).weight : null; }
function speak(text){ if(!data.sound || !('speechSynthesis' in window)) return; speechSynthesis.cancel(); const message=new SpeechSynthesisUtterance(text); message.rate=.98; message.pitch=.95; speechSynthesis.speak(message); }

function render(){
  const w=week(), [work,rest]=intervals(), current=currentWeight(), lost=current ? Math.max(0,107-current) : 0;
  document.querySelector('#week-label').textContent=`WEEK ${w} OF 12`;
  document.querySelector('#programme-progress').style.width=`${Math.max(8,((w-1)/12)*100)}%`;
  document.querySelector('#current-weight').innerHTML=current?`${current.toFixed(1)} <em>kg</em>`:`— <em>kg</em>`;
  document.querySelector('#week-target').innerHTML=`${TARGETS[w-1].toFixed(1)} <em>kg</em>`;
  document.querySelector('#streak-value').textContent=`${streak()} day${streak()===1?'':'s'}`;
  document.querySelector('#sessions-value').textContent=data.sessions.length;
  document.querySelector('#lost-value').textContent=`${lost.toFixed(1)} kg`;
  document.querySelector('#latest-weight').textContent=current?`${current.toFixed(1)} kg`:'— kg';
  const prescribed=workoutForToday(); document.querySelector('#today-workout-name').textContent=prescribed; document.querySelector('#today-workout-detail').textContent=`10 minutes · ${work} sec work / ${rest} sec recover`;
  renderHabits(); renderWorkoutPicker(); renderWeights(); document.querySelector('#sound-button').textContent=`Sound: ${data.sound?'on':'off'}`;
}
function renderHabits(){ const holder=document.querySelector('#habits-list'), checked=data.habits[today()]||{}; holder.innerHTML=HABITS.map((h,i)=>`<div class="habit"><label><input data-habit="${i}" type="checkbox" ${checked[i]?'checked':''}><span>${h}</span></label></div>`).join(''); document.querySelector('#habit-score').textContent=`${Object.keys(checked).filter(k=>checked[k]).length} / 6`; holder.querySelectorAll('input').forEach(input=>input.addEventListener('change',e=>{const d=data.habits[today()]||{};d[e.target.dataset.habit]=e.target.checked;data.habits[today()]=d;save()})); }
function renderWorkoutPicker(){ const [work,rest]=intervals(); document.querySelector('#workout-picker').innerHTML=Object.entries(PROGRAMME).map(([name,v])=>`<button class="workout-choice ${name===selectedWorkout?'active':''}" data-workout="${name}"><span class="emoji">${v.emoji}</span><span><strong>${name}</strong><small>${v.exercises[0]} · ${work}/${rest}</small></span></button>`).join(''); document.querySelectorAll('[data-workout]').forEach(b=>b.addEventListener('click',()=>{selectedWorkout=b.dataset.workout;renderWorkoutPicker()})); }
function renderWeights(){ const rows=[...data.weights].slice(-8); const chart=document.querySelector('#weight-chart'), history=document.querySelector('#weight-history'); if(!rows.length){chart.innerHTML='<p class="small-note">Log a weigh-in to start your chart.</p>';history.innerHTML='<p class="small-note">No check-ins yet.</p>';return} const vals=rows.map(r=>r.weight),min=Math.min(...vals,99),max=Math.max(...vals,107);chart.innerHTML=rows.map(r=>`<div class="chart-bar" style="height:${Math.max(20,((r.weight-min)/(max-min||1)*115)+35)}%"><span>${r.weight}</span></div>`).join(''); history.innerHTML=[...rows].reverse().map(r=>`<div class="history-row"><span>${dateText(r.date)} ${r.waist?`<small>· ${r.waist} cm waist</small>`:''}</span><strong>${r.weight.toFixed(1)} kg</strong></div>`).join(''); }
function openPage(page){ stopTimer(); document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===page));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.go===page));window.scrollTo({top:0,behavior:'smooth'});if(page==='workout') resetWorkoutView(); }
function resetWorkoutView(){ document.querySelector('#workout-setup').classList.remove('hidden');document.querySelector('#timer-view').classList.add('hidden');document.querySelector('#complete-view').classList.add('hidden');selectedWorkout=workoutForToday();renderWorkoutPicker(); }
function startWorkout(){ const [work,rest]=intervals(); const e=PROGRAMME[selectedWorkout].exercises; timerState={phase:'work',index:0,round:1,remaining:work,work,rest,exercises:e,paused:false};document.querySelector('#workout-setup').classList.add('hidden');document.querySelector('#timer-view').classList.remove('hidden'); speak(`Welcome to Project Under 100. ${selectedWorkout}. Round one. ${e[0]}. Three, two, one, go.`); paintTimer(); timer=setInterval(tick,1000); }
function tick(){ if(timerState.paused)return;timerState.remaining--; if(timerState.phase==='work'&&[20,10].includes(timerState.remaining))speak(timerState.remaining===20?'Halfway.':'Ten seconds remaining.'); if(timerState.remaining<=0) advanceTimer();paintTimer(); }
function advanceTimer(){ const s=timerState;if(s.phase==='work'){s.phase='rest';s.remaining=s.rest;speak(`Recover. Next: ${s.exercises[(s.index+1)%s.exercises.length]}.`)}else{if(s.index===s.exercises.length-1){if(s.round===2){finishWorkout();return}s.round++;s.index=0;speak(`Round two. ${s.exercises[0]}. Go.`)}else{s.index++;speak(`${s.exercises[s.index]}. Go.`)}s.phase='work';s.remaining=s.work;} }
function paintTimer(){const s=timerState;if(!s)return;const duration=s.phase==='work'?s.work:s.rest;document.querySelector('#timer-value').textContent=`00:${String(s.remaining).padStart(2,'0')}`;document.querySelector('#timer-ring').style.background=`conic-gradient(${s.phase==='work'?'var(--lime)':'var(--orange)'} ${((s.remaining/duration)*360)}deg,#263b33 0deg)`;document.querySelector('#timer-round').textContent=`ROUND ${s.round} OF 2`;document.querySelector('#timer-stage').textContent=s.phase==='work'?'WORK':'RECOVER';document.querySelector('#exercise-label').textContent=s.phase==='work'?`EXERCISE ${s.index+1} OF 5`:'RECOVERY';document.querySelector('#timer-exercise').textContent=s.phase==='work'?s.exercises[s.index]:'Take a breath';document.querySelector('#timer-next').textContent=s.phase==='work'?`Next: ${s.exercises[(s.index+1)%5]}`:'Get set for the next move';document.querySelector('#pause-button').textContent=s.paused?'RESUME':'PAUSE';}
function stopTimer(){if(timer)clearInterval(timer);timer=null;timerState=null;if('speechSynthesis'in window)speechSynthesis.cancel();}
function finishWorkout(){stopTimer();if(!data.sessions.some(s=>s.date===today()&&s.type===selectedWorkout))data.sessions.push({date:today(),type:selectedWorkout});const h=data.habits[today()]||{};h[2]=true;data.habits[today()]=h;localStorage.setItem(KEY,JSON.stringify(data));render();document.querySelector('#timer-view').classList.add('hidden');document.querySelector('#complete-view').classList.remove('hidden');speak('Workout complete. Outstanding effort. Under 100 is getting closer.');}

document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>openPage(b.dataset.go)));document.querySelector('#start-todays-workout').addEventListener('click',()=>{openPage('workout');selectedWorkout=workoutForToday();renderWorkoutPicker()});document.querySelector('#begin-workout').addEventListener('click',startWorkout);document.querySelector('#pause-button').addEventListener('click',()=>{timerState.paused=!timerState.paused;paintTimer()});document.querySelector('#skip-button').addEventListener('click',()=>{advanceTimer();paintTimer()});document.querySelector('#sound-button').addEventListener('click',()=>{data.sound=!data.sound;save()});document.querySelector('#weight-date').value=today();document.querySelector('#weight-form').addEventListener('submit',e=>{e.preventDefault();const date=document.querySelector('#weight-date').value,weight=Number(document.querySelector('#weight-input').value),waist=Number(document.querySelector('#waist-input').value)||null;data.weights=data.weights.filter(x=>x.date!==date);data.weights.push({date,weight,waist});data.weights.sort((a,b)=>a.date.localeCompare(b.date));e.target.reset();document.querySelector('#weight-date').value=today();save()});document.querySelector('#reset-button').addEventListener('click',()=>{if(confirm('Reset all local progress from this device?')){localStorage.removeItem(KEY);data=load();save();}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;document.querySelector('#install-button').classList.remove('hidden')});document.querySelector('#install-button').addEventListener('click',async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;document.querySelector('#install-button').classList.add('hidden')}});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js'));render();
